image: node:20

stages:
  - install
  - build
  - package
  - deploy

install:
  stage: install
  script:
    - npm install

build:
  stage: build
  script:
    - npm run build

package:
  stage: package
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Construction de l'image Docker"

deploy:
  stage: deploy
  script:
    - echo "Déploiement terminé"
  only:
    - main

notify_success:
  stage: deploy
  script:
    - echo "Pipeline réussi"
  when: on_success

notify_failure:
  stage: deploy
  script:
    - echo "Pipeline échoué"
  when: on_failure